<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <DisableImplicitNuGetFallbackFolder>true</DisableImplicitNuGetFallbackFolder>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="kentico.xperience.admin" Version="31.7.2" />
    <PackageVersion Include="kentico.xperience.webapp" Version="31.7.2" />
    <PackageVersion Include="kentico.xperience.mjml" Version="31.7.2" />
    <PackageVersion Include="kentico.xperience.cloud" Version="31.7.2" />
    <PackageVersion Include="kentico.xperience.azurestorage" Version="31.7.2" />
    <PackageVersion Include="kentico.xperience.imageprocessing" Version="31.7.2" />
    <PackageVersion Include="SonarAnalyzer.CSharp" Version="10.20.0.135146" />
    <PackageVersion Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.23.0" />
    <PackageVersion Include="XperienceCommunity.SqlBrowser" Version="5.0.0" />
  </ItemGroup>
</Project>